name: Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: panthutk  # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build images
        run: docker compose -f docker-compose.yml build

      - name: Push Backend
        run: |
          docker tag todo101-todo-backend panthutk/todo-backend:latest
          docker push panthutk/todo-backend:latest

      - name: Push Frontend
        run: |
          docker tag todo101-todo-frontend panthutk/todo-frontend:latest
          docker push panthutk/todo-frontend:latest
